In [ ]:
import matplotlib.pyplot as plt
import mplcursors
import numpy as np
from matplotlib.patches import Rectangle

In [ ]:
%matplotlib widget

In [ ]:
class InteractiveScatterPlot:
    def __init__(self, data):
        self.data = data  # Store the data passed to the class
        self.fig, self.ax = plt.subplots()  # Create a figure and axes for the plot
        self.scatter = self.ax.scatter(data[:, 0], data[:, 1])  # Create a scatter plot with the data
        self.selected_indices = set()  # Maintain a set of selected point indices

        self.fig.canvas.mpl_connect('button_press_event', self.on_button_press)
        # Connect the 'button_press_event' event to the 'on_button_press' method

    def on_button_press(self, event):
        if event.button == 1:  # If the left mouse button is pressed
            contains, ind = self.scatter.contains(event)
            # Check if the event occurred inside a scatter point and get the indices of the points
            if contains:
                ind = ind['ind'][0]  # Get the index of the selected point
                if ind in self.selected_indices:
                    self.selected_indices.remove(ind)  # Deselect the point if it was already selected
                else:
                    self.selected_indices.add(ind)  # Select the point if it was not already selected
                self.update_plot()  # Update the scatter plot to reflect the selection changes

        elif event.button == 3:  # If the right mouse button is pressed
            if len(self.selected_indices) > 0:
                self.data = np.delete(self.data, list(self.selected_indices), axis=0)
                self.selected_indices.clear()
                self.update_plot()

    def update_plot(self):
        self.scatter.set_offsets(self.data)  # Update the positions of the scatter points
        self.scatter.set_alpha(0.5)  # Set the transparency of the scatter points
        self.scatter.set_sizes([20] * len(self.data))  # Set the size of the scatter points
        self.scatter.set_array(np.array([ind in self.selected_indices for ind in range(len(self.data))]))
        # Color the scatter points based on whether they are selected or not
        self.fig.canvas.draw()  # Redraw the plot to reflect the changes

    def save_data(self, filename):
        np.save(filename, self.data)  # Save the data to a .npy file



In [ ]:
class InteractiveScatterPlot:
    def __init__(self, data):
        self.data = data
        self.fig, self.ax = plt.subplots()
        self.scatter = self.ax.scatter(data[:, 0], data[:, 1])
        self.selected_indices = set()
        self.dragging = False
        self.start_point = None
        self.end_point = None

        self.fig.canvas.mpl_connect('button_press_event', self.on_button_press)
        self.fig.canvas.mpl_connect('motion_notify_event', self.on_motion_notify)
        self.fig.canvas.mpl_connect('button_release_event', self.on_button_release)

    def on_button_press(self, event):
        if event.button == 1:  # Left mouse button
            contains, _ = self.scatter.contains(event)
            if contains:
                ind = self.get_index(event)
                if ind is not None:
                    if ind in self.selected_indices:
                        self.selected_indices.remove(ind)
                    else:
                        self.selected_indices.add(ind)
                    self.update_plot()
            self.dragging = True
            self.start_point = (event.xdata, event.ydata)

        elif event.button == 3:  # Right mouse button
            if len(self.selected_indices) > 0:
                self.data = np.delete(self.data, list(self.selected_indices), axis=0)
                self.selected_indices.clear()
                self.update_plot()

    def on_motion_notify(self, event):
        if self.dragging:
            self.end_point = (event.xdata, event.ydata)
            self.select_points_in_region()
            self.update_plot()

    def on_button_release(self, event):
        if event.button == 1:  # Left mouse button
            self.dragging = False
            self.start_point = None
            self.end_point = None

    def get_index(self, event):
        try:
            return event.ind[0]
        except AttributeError:
            contains, ind = self.scatter.contains(event)
            if contains:
                return ind['ind'][0]
        return None

    def select_points_in_region(self):
        if self.start_point and self.end_point:
            x_min, x_max = sorted([self.start_point[0], self.end_point[0]])
            y_min, y_max = sorted([self.start_point[1], self.end_point[1]])

            selected_indices = []
            for ind, (x, y) in enumerate(self.data):
                if x_min <= x <= x_max and y_min <= y <= y_max:
                    selected_indices.append(ind)

            self.selected_indices = set(selected_indices)

    def update_plot(self):
        self.scatter.set_offsets(self.data)
        self.scatter.set_alpha(0.5)
        self.scatter.set_sizes([2] * len(self.data))
        self.scatter.set_array(np.array([ind in self.selected_indices for ind in range(len(self.data))]))
        self.fig.canvas.draw()

In [ ]:
# create a sine plot with noise data with 10000 points
x = np.linspace(0, 10, 10000)
y = np.sin(x) + np.random.normal(0, 0.1, 10000)
data = np.array([x, y]).T

# # Load data from .npy file
# data = np.load('your_file.npy')

# Create interactive scatter plot
plot = InteractiveScatterPlot(data)

# Show the plot
plt.show()


: 

In [ ]:
# Save the resulting data after closing the plot
plot.save_data('result.npy')

In [ ]:
# # create a dummy sine wave data
# x = np.linspace(0, 10, 100)
# y = np.sin(x)

# # save as .npy file
# np.save('your_file.npy', np.array([x, y]).T)


In [ ]:
# # load the data
result = np.load('result.npy')

# # scatter plot the data
plt.scatter(result[:, 0], result[:, 1])
plt.show()


In [21]:
# import and print newData.npy

import numpy as np
import matplotlib.pyplot as plt

# load the data
data = np.load('newData.npy')
data_removed = np.load('newData_removed.npy')
print(data)
print(data.shape)
print()
print(data_removed)
print(data_removed[0].shape)
# scatter plot the data
# plt.scatter(data[:, 0], data[:, 1])
# plt.scatter(data_removed[:, 0], data_removed[:, 1])
# plt.show()


[[ 0.00000000e+00  0.00000000e+00]
 [ 1.11111111e-01  6.42787610e-01]
 [ 2.22222222e-01  9.84807753e-01]
 [ 3.33333333e-01  8.66025404e-01]
 [ 6.66666667e-01 -8.66025404e-01]
 [ 7.77777778e-01 -9.84807753e-01]
 [ 8.88888889e-01 -6.42787610e-01]
 [ 1.00000000e+00 -2.44929360e-16]]
(8, 2)

[[[ 0.44444444  0.34202014]
  [ 0.55555556 -0.34202014]]]
(2, 2)


In [7]:
array1 = np.array([1, 2, 3, 4, 5])
# delete the first and last element of array1
array2 = np.delete(array1, [0, 4])

# difference between array1 and array2
diff = np.setdiff1d(array1, array2)

# print the difference
print(diff)


[1 5]


In [15]:
# 2d numpy array
array1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# delete the first column of array1
array2 = np.delete(array1, 0, 1)

# difference between array1 and array2
diff = np.setdiff1d(array1, array2)

# print the difference
print(diff)

# create a new array out of indices
array3 = np.array([1, 2, 3, 4, 5])
indices = set([0, 2, 4])
array4 = array3[list(indices)]

# print the new array
print(array4)



[1 6]
[1 3 5]


In [25]:
sr = 1
duration = 10
t1 = np.linspace(0, duration-1, int(sr * duration))
t1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [2]:
import os

# get current working directory
cwd = os.getcwd()
print(cwd)
# go one directory back
os.chdir('..')
# get current working directory
cwd = os.getcwd()
print(cwd)

d:\InteractivePlots
d:\
